### ISSUE TITLE
Is it possible for an RDF* triple to be its own subject or object?

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star#1]
In other word, can we represent in the RDF* *abstract syntax* (I know we can't in Turtle*), something like

  " This sentence was stated by Pierre-Antoine."

More formally, the definition http://ceur-ws.org/Vol-1912/paper12.pdf states that if *t* is an RDF* triple, *p* is an IRI and *o* a literal, then *(t p o)* is an RDF* triple. But then, t could be *(t p o)* itself...

Of course, the question extends to "indirect containment", like *t = ((t p o) p' o')*...

@hartig I have a strong feeling that this was *not* your intention, but I'd rather check with you, before I make an explicit note in the document that this is not allowed...

**Comment by hartig** [comment]
Indeed, this is not the intention of the definition. Notice that this form of definition is a standard approach to recursively define syntactic constructs. You can think of it to be an alternative to writing down the grammar in something like [EBNF](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form). In such definitions, there is never the assumption/intention that some expression may contain itself as a sub-expression.

As another example of such a recursive definition, take a look at the seminal [paper about SPARQL by Perez et al.](https://marceloarenas.cl/publications/tods09a.pdf) At the top of page 5, that paper defines the notion of a SPARQL graph pattern expression and the second point uses recursion.

**Comment by VladimirAlexiev** [comment]
The spec now explicitly excludes recursive rdf* triples.
But how about SPARQL*? AFAIK there's nothing to prevent someone from writing 
```
<<?x p o>> q ?x
```
I guess this won't match anything. Are we happy with that?

How about
```
BIND(<<?x p o>> as ?x)
```
Is this why we need FIND vs BIND? cc @pklinov

**Comment by klinovp** [comment]
I am personally pretty comfortable with `<<?x p o>> q ?x` not matching anything on any data. 

Re: `BIND(<<?x p o>> as ?x)`, no, this isn't why I thought overriding `BIND` was a bad idea (FIND makes sense to me). I'd rather think `BIND(<<?x p o>> as ?x)` should be syntactically invalid, similar to how SPARQL prohibits setting variables in a BIND which are used before it.

**Comment by hartig** [comment]
@VladimirAlexiev what's wrong with

```
 <<?x p o>> q ?x
```
?

There is nothing recursive in it. I mean, it is not a triple* pattern that contains itself (which would also not be possible, by definition). 

Or, are you worried by the fact that this (nested) triple* pattern uses the same variable twice? I don't see a problem with this. In contrast, assume `p` is foaf:knows, `o` is ex:Bob, and `q` is ex:says. So, you are asking for everyone who says that he/she knows Bob, which is a perfectly possible use case to me.

**Comment by pchampin** [comment]
@VladimirAlexiev 
I agree with @hartig regarding ``<<?x p o>> q ?x``.

``BIND(<<?x p o>> as ?x)`` is more tricky, though, but maybe not more than ``BIND(?x+1 as ?x)``... FTR, the latter *is* valid SPARQL (which surprised me a lot), and yields different results on the 3 systems on which I tested it (which didn't suprise me at all :smiling_imp: ).
