### ISSUE TITLE
the final report should include a complete grammar for any changed media type

### ISSUE THREAD

**Issue by lisp** [w3c/rdf-star#104]
while it would be helpful to include isolated grammar changes inline in the text, to have complete grammars for any modified and/or supplanted media types would facilitate implementation.

**Comment by gkellogg** [comment]
Perhaps we can maintain separate HTML and EBNF files with the complete grammars and reference them from the spec?

If existing tools aren't working, [I have tools](https://github.com/dryruby/ebnf) to generate an HTML version of the EBNF grammars. (See, for example the [N3 grammar](https://w3c.github.io/N3/spec/#grammar)).

**Comment by afs** [comment]
This is the tool chain used for SPARQL 1.0 and 1.1.
https://github.com/apache/jena/tree/main/jena-arq/Grammar

It starts with a grammar that is checked and executable - given the size of the grammar, the checking is quite important.
Then to HTML via a text form which protects quoting and keeps terminal separate from grammar productions.  A text copy of the HTML is closest to EBNF.

It is most useful if the numbering in the EBNF aligns to the numbering in the SPARQL 1.1 spec. That is some manual adjustment so better done after the spec is stable. Also - the Turtle grammar references SPARQL numbering. If it is feasible, we should keep this for "-star" forms.

**Comment by gkellogg** [comment]
FWIW, the grammar I'm using is at https://github.com/ruby-rdf/sparql/blob/develop/etc/sparql11.bnf and rendered in HTML [here](http://ruby-rdf.github.io/sparql/etc/sparql11.html).

**Comment by afs** [comment]
That BNF seems to exclude paths in annotations blocks even if used in a part of the query pattern that allows paths.

test case: 
```
SELECT * {
  ?x :p ?o {| :q/:r ?z |} .
  }
```
and it could have further structure, `?x :p ?o {| :q [ :rdfs:subClassOf*/rdf:type ?T ]  |}`.

There are two cases: one with `PropertyListNotEmpty` inside, used from `Object` (for templates e.g. CONSTRUCT) and one with `PropertyListPathNotEmpty` used from `ObjectPath` inside for the WHERE clause.

```
ObjectPath        ::= GraphNodePath AnnotationPath ?
AnnotationPath    ::= "{|" PropertyListPathNotEmpty "|}"

Object            ::= GraphNodePath Annotation?
Annotation        ::= ( "{|" PropertyListNotEmpty "|}" )?
```

**Comment by gkellogg** [comment]
Yes, I think I that `AnnotationPattern` should have been `'{|' PropertyListPathNotEmpty '|}'` not `PropertyListNotEmpty`. This is symmetrical with the Turtle gramma where rather than putting the annotation on `object`, it's on `objectList`.

So, the changes in my grammar would be the following:

    [79]  ObjectList              ::= Object Annotation? ( ',' Object Annotation? )*
    [86]  ObjectListPath          ::= ObjectPath AnnotationPattern? ( ',' ObjectPath AnnotationPattern? )*
    [177]	Annotation	      ::=	'{|' PropertyListNotEmpty '|}'
    [177p]	AnnotationPattern	      ::=	'{|' PropertyListNotEmpty '|}'

I believe that parses this particular case, and has the advantage of being closer to the Turtle `objectList` production, but perhaps it misses some cases.

**Comment by gkellogg** [comment]
I think those changes do it. I get the following ASTs:

For `?x :p ?o {| :q/:r ?z |} .`:
```
(join
  (bgp (triple ?x :p ?o))
  (path (triple ?x :p ?o) (seq :q :r) ?z))
```

And for `?x :p ?o {| :q [ rdfs:subClassOf*/rdf:type ?T ] |}.`:
```
(join
  (bgp (triple ?x :p ?o))
  (path (triple ?x :p ?o)
    (seq (path* rdfs:subClassOf) rdf:type)
    ?T))
```

**Comment by afs** [comment]
The other case here is templates which are pathless -- `CONSTRUCT { :s :p :o {| :q :z |} }` (and INSERT, DELETE).

`ObjectList` is used in templates.
`ObjectListPath` in patterns.

(previous example fixed)

**Comment by hartig** [comment]
Andy, Gregg, I see your discussion here only now. I had already extended the PR based on Andy's comment there. See my response to Andy's comment in the PR: https://github.com/w3c/rdf-star/pull/65#discussion_r579540076

**Comment by afs** [comment]
Discussions now on #106 together with the editor's changes.

**Comment by hartig** [comment]
I am re-opening this issue again to keep it as a reminder of James' initial request. 

(the discussion in #106 is about the annotation syntax in SPARQL-star)

**Comment by pchampin** [comment]
I propose to defer this to the future WG (which will have, anyway, to update each concerned grammar accordingly)
