### ISSUE TITLE
Decide on a policy for editorship/authorship

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star#11]
Although the document has currently two editors and two authors, nothing is fixed in that respect.
We have to collectively decide what criteria we chose to decide who's an editor, who's an author, and even if we want to make a distinction between the two.

**Comment by gatemezing** [comment]
Well, we already have 3 authors in the latest semantics draft (2020/11/12), so maybe something is already on the way to solve this issue?!

**Comment by TallTed** [comment]
Possibly [a useful starting point](https://www.w3.org/Signature/Contributor.html)...

**Comment by pchampin** [comment]
@gatemezing 
The role of this issue precisely is to make it clear that the current editor/author assignment is not definitive. And also to not forget to discuss it at some point.

**Comment by akuckartz** [comment]
Maybe an additional category of "other contributors" can be added? (I am somewhat proud for my successful suggestion to rename the specification ;-)

**Comment by hartig** [comment]
@pchampin do you know whether there is a contributors category in Respec?

**Comment by gkellogg** [comment]
Ore common is to have an acknowledgements appendix to list active members of the CG and any special notes the editors would like to make.

**Comment by hartig** [comment]
Thanks Gregg. However, I wouldn't want it to be hidden away in some appendix. A list of contributors directly below the editors and authors list would be better.

**Comment by akuckartz** [comment]
A spec with a contributors section: https://www.w3.org/TR/2012/REC-owl2-direct-semantics-20121211/

An issue with some background regarding ReSpec
https://github.com/w3c/respec/issues/152

**Comment by hartig** [comment]
Thanks @akuckartz -- I think we can use that. What is your affiliation?

**Comment by pchampin** [comment]
This as somehow solved when releasing our first public draft. We must not forget to update the Editor/Author/Contributor lists at each publication, but I believe this issue can be closed.
