### ISSUE TITLE
Expansion of the annotation syntax in Turtle-star not defined

### ISSUE THREAD

**Issue by hartig** [w3c/rdf-star#112]
Looking at Section 3.1.2, I cannot find any mention of how the annotation syntax in Turtle-star maps to an RDF-star graph. However, I may be missing something because this section is really hard to read. @gkellogg can you clarify how the expansion of the annotation syntax short hand is currently captured in the spec.

**Comment by gkellogg** [comment]
I think the section correctly describes required behavior for both embedded triples and annotations in a style consistent with that used in [7.3 RDF Triples Constructors](https://www.w3.org/TR/turtle/#sec-parsing-triples) of the Turtle Spec. But, particularly taken out of context, it doesn't help to get an intuitive understanding.

I can add an informative 3.1.2.1 Overview subsection that attempts to help with the intuition of what the subsequent steps do, and then for clarity, we can move the paragraphs starting with A "Turtle-star document defines an RDF-star graph ..." into a new 3.1.2.2 RDF-star Triples Constructors subsection.

**Comment by hartig** [comment]
Yes, that will be helpful for readers. Thanks! 

 This overview subsection may include a few examples of the most typical cases. Or, perhaps, the corresponding test suite may be enough in terms of examples.

**Comment by gkellogg** [comment]
In don’t think people usually look to the test suite for examples, but we should have some tests that can inform a couple of choice examples in that section.
