### ISSUE TITLE
Typo in section 4.3.2

### ISSUE THREAD

**Issue by mark-watson** [w3c/rdf-star#119]
I believe that the last line is incorrect, it should start with <<?c a owl:Class>>

For instance, the following syntax expression:
EXAMPLE 5
<<?c a owl:Class>> dct:source ?src ;
    :entailing <<?c a rdfs:Class>> .
must be expanded to
EXAMPLE 6
<<?c a owl:Class>> dct:source ?src .
<<?c a rdfs:Class>> :entailing <<?c a rdfs:Class>> .

**Comment by hartig** [comment]
Thanks Mark! You are right. We had already fixed this issue in our editors' draft ;-)

https://w3c.github.io/rdf-star/cg-spec/editors_draft.html#example-10-expanding-abbreviations-for-triple-patterns-with-embedded-triple-patterns
