### ISSUE TITLE
Time-sensitive data use case

### ISSUE THREAD

**Issue by edulemasson** [w3c/rdf-star#120]
As a Big Data and & AI platform-product owner
I want the capacity to describe and query relations in the graph with the dimension of temporal entity-events.

So that we could extract more power from the Graph, using relationships over time in stuff like job-assignment, seasonal events, and so on. In a website with a lot of annotated entities in each page and with the users navigating in that contents over time, we could also look into the user and its semantics data over time too.

So we could ask the RDF-star this kind of quotes: 
- "What is the semantic classes or entities for the user X with more consumption in the last 7 days"
- "What is the last job for the user X?"
- "What is the last edition of the program Y"

**Comment by afs** [comment]
Hi - thanks for the use case. I've added to the "Use Cases and Requirements" document.

https://w3c.github.io/rdf-star/UCR/rdf-star-ucr.html#time-sensitive-data-use-case
