### ISSUE TITLE
Uncertainty representation

### ISSUE THREAD

**Issue by djebR** [w3c/rdf-star#132]
As a Ph.D. student working on uncertainty,
I want to use RDF* to represent uncertainty values for RDF statements, using mUnc ontology,
This offers the possibility to evaluate the reliability of statements in a specific context.

following this: http://ns.inria.fr/munc/

**Comment by hartig** [comment]
Hi @djebR ! You may be interested in the following related work about capturing and querying uncertainty for individual RDF statements based on RDF*. While this work is in the context of RDF stream processing, the concepts carry over to the static case as well. The main paper about this work is:

* Robin Keskisärkkä, Eva Blomqvist, Leili Lind, and Olaf Hartig: [Capturing and Querying Uncertainty in RDF Stream Processing](http://olafhartig.de/files/KeskisarkkaEtAl_EKAW2020_Preprint.pdf). In Proceedings of the 22nd International Conference on Knowledge Engineering and Knowledge Management (EKAW), 2020.

**Comment by djebR** [comment]
Indeed, I attended that presentation and the author mentioned that use case and mUnc ontology in the perspectives. Unfortunately, we didn't have the time to discuss it.

I am planning on including RDF* as the main way to annotate statements with uncertainty values.

**Comment by afs** [comment]
Hi there - the use case has been added to the UCR document.

It would be good to hear your thoughts on RDF-star (the work of this group) where the triple statement mentioned is not also asserted and whether this can form a useful basis for use with mUnc.

**Comment by djebR** [comment]
> 
> 
> Hi there - the use case has been added to the UCR document.
> 
> It would be good to hear your thoughts on RDF-star (the work of this group) where the triple statement mentioned is not also asserted and whether this can form a useful basis for use with mUnc.

One example I can think of is to assert the appartenance of an embedded triple to the context (the World) it was declared in. 
`<<ex:Apple ex:hasColor ex:Red>> munc:inWorld ex:World_1 {| munc:hasMeta [a munc:Uncertainty; ... ] |}`
