### ISSUE TITLE
reach out for the community about adding an IRI to the rdf: namespace

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star#134]
As decided during call:
https://w3c.github.io/rdf-star/Minutes/2021-03-12.html#x117

This is related to #102

**Comment by pchampin** [comment]
done at: https://www.w3.org/mid/368d0629-fb7c-4ff8-1dfe-f7c93bbd7f04@ercim.eu

**Comment by TallTed** [comment]
A somewhat-less opaque link to the relevant message -- 
https://lists.w3.org/Archives/Public/semantic-web/2021Mar/0034.html

**Comment by ericprud** [comment]
> A somewhat-less opaque link to the relevant message --
> https://lists.w3.org/Archives/Public/semantic-web/2021Mar/0034.html

Meta: I encourage people to use MID links as they are intrinsic to the message, as well as useful to the reader (I use IMAP to fetch messages by MID). "0034" has no intrinsic grounding in the message and is at the mercy of order of mbox entries.
