### ISSUE TITLE
meta-issue: link from RDF-DEV CG page should go to github.io, not github.com

### ISSUE THREAD

**Issue by TallTed** [w3c/rdf-star#150]
On <https://www.w3.org/community/rdf-dev/>, there's a **w3c/rdf-star** anchor which has an `href` of <https://github.com/w3c/rdf-star>.

<https://github.com/w3c/rdf-star> is not a visitor-friendly page, and it isn't easy to find the link to <https://w3c.github.io/rdf-star/>, which we've worked to make visitor-friendly.

I think the `href` for **w3c/rdf-star** on <https://www.w3.org/community/rdf-dev/> should be changed to target <https://w3c.github.io/rdf-star/>.

Alternatively, the content of <https://w3c.github.io/rdf-star/> could be re-worked into a replacement README for <https://github.com/w3c/rdf-star>, which might or might not include the current table of preliminary implementations (which should probably be shifted from being the primary README in any case).

**Comment by pchampin** [comment]
The link on the CG page is probably automatically genarated, and is meant to link to a github repo. So I don't think we can (or should) change it.

However, I wholeheartedly agree that 1) the readme should be reworked to point explicitly to our landing page, and 2) the table should be moved out of the README into our site.

**Comment by TallTed** [comment]
I think I'm OK with this handling of things.  And this can be closed when #152 gets merged.
