### ISSUE TITLE
Issues running EARL report generator

### ISSUE THREAD

**Issue by afs** [w3c/rdf-star#153]
Capturing points discovered while preparing a EARL PR:

1. The instructions say `/releases` but other reports are in `/reports`. But `/reports` is also the directory for the HTML production.
1. They are not linked to on the home page.
1. There are lot of stray red "X" on the reports. (these go away when there is more than one system in a section)
1. `doap:developer` may be a blank node.

**Comment by pchampin** [comment]
the red "X"s indicate that we don't have two implementations passing that test (which is the success criterion on most RECs). In our case, we can probably disable this feature...

**Comment by gkellogg** [comment]
> Capturing points discovered while preparing a EARL PR:
> 
> 1. The instructions say `/releases` but other reports are in `/reports`. But `/reports` is also the directory for the HTML production.

/reports is correct.

> 2. They are not linked to on the home page.

they should be, but more importantly, they’re linked from the spec.

> 3. There are lot of stray red "X" on the reports. (these go away when there is more than one system in a section)

what PA said.

> 4. `doap:developer` may be a blank node.

That should be okay.

**Comment by pchampin** [comment]
@afs can we close this issue, or is there still a problem?

**Comment by afs** [comment]
It's not a problem any longer.

The red 'X's were my misunderstanding.
The other points have been addressed.

**Comment by gkellogg** [comment]
The red 'X's are implemented in the Haml template, as it was useful for WGs to know when there a feature is considered widely implemented. That doesn't apply for CGs, so we could easily update the template to not show the 'X's.

**Comment by afs** [comment]
Now I understand their purpose, I'm fine with the status quo - I has assumed they marked an error in processing.
