### ISSUE TITLE
The SPARQL-star grammar does not cover nested triple syntax in expressions

### ISSUE THREAD

**Issue by Tpt** [w3c/rdf-star#163]
The current SPARQL-star grammar does not seems to cover the [`sparql-star-expr-1`](https://w3c.github.io/rdf-star/tests/sparql/syntax/manifest.html#sparql-star-expr-1) test case:

```sparql
SELECT * {
  ?s ?p ?o .
  BIND(<<?s ?p ?o>> AS ?t)
}
```

Indeed, I do not see in the current drafpt any change of the [`Expression`](https://www.w3.org/TR/sparql11-query/#rExpression) grammar production of any of its nested productions. I believe the [`PrimaryExpression`](https://www.w3.org/TR/sparql11-query/#rPrimaryExpression) production should be updated to included RDF-star nest triples as well.

**Comment by afs** [comment]
Thanks for the report. Indeed, `<< >>` should be in `PrimaryExpression`.

**Comment by afs** [comment]
Done with PR #167
