### ISSUE TITLE
add a paragraph on SPARQL service description and sd:feature

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star#164]
Assigned during today's call: https://w3c.github.io/rdf-star/Minutes/2021-04-30.html#a01

**Comment by TallTed** [comment]
As noted in the minutes, I think these are more relevant than `sd:feature`, per se:

* [sd:SPARQL10Query](https://www.w3.org/TR/sparql11-service-description/#lang-sparql10query)
* [sd:Language](https://www.w3.org/TR/sparql11-service-description/#sd-Language)
* [sd:Feature](https://www.w3.org/TR/sparql11-service-description/#sd-Feature)

**Comment by gatemezing** [comment]
> As noted in the minutes, I think these are more relevant than `sd:feature`, per se:
> 
> * [sd:SPARQL10Query](https://www.w3.org/TR/sparql11-service-description/#lang-sparql10query)
> * [sd:Language](https://www.w3.org/TR/sparql11-service-description/#sd-Language)
> * [sd:Feature](https://www.w3.org/TR/sparql11-service-description/#sd-Feature)

They are kind of all related according to their semantics in RDFS.
```
sd:Language rdfs:subClassOf sd:Feature .
sd:SPARQL10Query a sd:Language. 
```

**Comment by TallTed** [comment]
Yes, they are related.  My point is that the more specific predicates and collective objects are more suited to communicating the specific differences/qualities of an RDF-star/SPARQL-star server vs a "typical" RDF/SPARQL server than the very granular `sd:feature`.  `sd:feature` should not be used with, for instance, `sd:SPARQLstarQuery`...

**Comment by gatemezing** [comment]
Would it be also worth it to also see the conformance in a dataset available on the Web in general, by using for e.g.,  `dcat:Dataset` ? The [dctat vocabulary ](https://www.w3.org/TR/vocab-dcat-3/#Class:Dataset) defines the notion of dcat:conformsTo and [dcterms:Standard](http://purl.org/dc/terms/Standard). This could help publishers describing their assets with that they dump dataset `dcterms:conformsTo` RDF-star.

**Comment by TallTed** [comment]
I have no objection to recommending `dcterms:conformsTo` be used as part of the description of any RDF-star (or RDF) serializations.  It might be helpful to describe RDF 1.0 vs 1.1 datasets.  That said, I doubt many publishers will add it to descriptions of existing (nor probably future) RDF serializations.  It's *slightly* more likely in serializations where the format allows for inline comments, like Turtle or N3, unlike JSON-LD, CBOR-LD, etc.
