### ISSUE TITLE
Actions for using "quoted triple" terminology

### ISSUE THREAD

**Issue by afs** [w3c/rdf-star#193]
Tasks for #184 ("quoted triple")

- [x] Update text and links in the editors draft
- [x] Update test suite, mainly `mf:name`
- [x] Add new material for non-normative explanation and examples.

**Comment by afs** [comment]
Status: 2021-07-07:

* PR #192 covers translating from "embedded" to "quoted".
* [Comment on #184](https://github.com/w3c/rdf-star/issues/184#issuecomment-873568469) identifies the test changes needed.
* [Comment on #184](https://github.com/w3c/rdf-star/issues/184#issuecomment-874748516) drafts some explanatory text and examples.

**Comment by gkellogg** [comment]
PR #192 also makes the test changes.
