### ISSUE TITLE
TopBraid EDG missing from list of implementations

### ISSUE THREAD

**Issue by akuckartz** [w3c/rdf-star#194]
https://www.topquadrant.com/rdf-star/ is not contained in this list: https://w3c.github.io/rdf-star/implementations.html

**Comment by akuckartz** [comment]
@HolgerKnublauch

**Comment by afs** [comment]
Currently, the group is seeking implementation reports: https://w3c.github.io/rdf-star/reports/index.html

**Comment by HolgerKnublauch** [comment]
Our support is limited to a variant of Turtle-star and we represent triple nodes with special URIs. No SPARQL support. What we have is pragmatically working well for customers but we are awaiting a more stable/final spec before investing more resources into it.

If that's enough for the list, please feel free to add a row with a link to https://www.topquadrant.com/rdf-star/ for documentation. We are too far off a formal implementation report at this stage.
