### ISSUE TITLE
referential opacity

### ISSUE THREAD

**Issue by pfps** [w3c/rdf-star#219]
There has been a lot of discussion in the CG on referential transparency / opacity and decisions made in this area that affect the behaviour of RDF*.

If a WG is going to go forward there should be re-examination of this issue.  However, the draft report pushes this important concept into the technical details of the semantics.

There should be discussion of the effects of the current semantics of RDF* in the introductory material of the document.   This will help WG members understand what RDF* is and, probably more importantly, is not.

**Comment by pchampin** [comment]
this was discussed during today's meeting: https://w3c.github.io/rdf-star/Minutes/2021-11-12.html#t04

**Comment by pchampin** [comment]
Closing as the discussion is continued on #225.
