### ISSUE TITLE
paring down the semantics

### ISSUE THREAD

**Issue by pfps** [w3c/rdf-star#220]
I just had a thought.

What would happen if there were only three added triples in the mapping instead of six, mapping to the literal mappings of IRIs and literals but to the actual blank nodes.  Would any entailments change?  Would there be any (significant) change to SPARQL results?

**Comment by pchampin** [comment]
I did think about it at the time, but came to the conclusion that it would not fly.

More precisely, we would like
```
:alice :mother :charlotte.
:alice :says << :charlotte :nickname "Charlie"  >>.
```
to entail
```
:alice :mother _:c.
:alice :says << _:c :nickname "Charlie" >>.
```
(this is a natural extension of the [interpolation lemma](https://www.w3.org/TR/rdf11-mt/#dfn-interpolation) in standard RDF).

But if the unstar mapping kept only lexical representation of the terms of the quoted triple, `_:c` in the second graph would have to be bound to I(:charlotte) to satisfy the 1st triple, and to I("<http://example.com/charlotte>") to satisfy the 2nd one.

**Comment by pchampin** [comment]
@pfps are you ok with closing this issue? Of, if you are still not convinced, to defer it to the future WG (we are not really planning on changing the semantics at that point...)?

**Comment by pfps** [comment]
Sure close.
