### ISSUE TITLE
suggest to Olaf and Bryan to update their paper on arXiv

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star#222]
as discussed during today's meeting: https://w3c.github.io/rdf-star/Minutes/2021-11-12.html#a02
assignee: @rdfguy

**Comment by pchampin** [comment]
This was discussed during today's call: https://w3c.github.io/rdf-star/Minutes/2021-12-03.html#t02

**Comment by hartig** [comment]
Done! See: https://arxiv.org/abs/1406.3399

I have add a block of text in red color at the top of the document. The text says:

_This document has become obsolete. The ideas and formalizations in this document have been picked up and developed further by a task force of the RDF-DEV community group at the World Wide Web consortium (W3C). In this context, the approach has been renamed to RDF-star and SPARQL-star. The main result of the group is a community group report that serves as a specification of the approach. Additionally, the group has developed a comprehensive collection of test suites for different RDF-star syntaxes, for the RDF-star semantics, and for SPARQL-star. Notice that there are some aspects in which RDF-star and SPARQL-star, as defined in the aforementioned specification, differ from RDF* and SPARQL* as defined in this document. Most notably, the semantics of embedded triples—which are now called quoted triples—is not anymore defined in terms of standard RDF reification and such a quoted triple is not anymore considered to be implicitly asserted in an RDF-star graph that contains nested triples of which the quoted triple is a constituent. Another difference is that the additional notion of BIND clauses as defined for SPARQL* in this document (cf. Example 4) has not been carried over to SPARQL-star (however, SPARQL-star has a new built-in function called TRIPLE which can be used for the same purpose)._

Additionally, I have added a shorter form of this text as the comment for the new version of the arXiv entry.
