### ISSUE TITLE
Test report generator failure

### ISSUE THREAD

**Issue by afs** [w3c/rdf-star#233]
In an up-to-date repo, `bundle install` and `bundle exec rake` run fine.

But I tried to add a new EARL report `apache-jena.ttl` I get errors relating to `"http://champin.net/#pa"` which isn't in the file.
(draft [apache-jena.ttl.txt](https://github.com/w3c/rdf-star/files/7739236/apache-jena.ttl.txt) attached - with `.txt` added for GH).

How can I debug this?

_Update_: PR #235 works - the difference is "homepage" URIs changed from "http:" to "https:" and if the timestamp of the file is later than all files in the directory. Restoring earl.* from git does not leave timestamps in the right state.

```
Traceback (most recent call last):
	9: from /home/afs/gems/bin/earl-report:23:in `<main>'
	8: from /home/afs/gems/bin/earl-report:23:in `load'
	7: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/bin/earl-report:100:in `<top (required)>'
	6: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/lib/earl_report.rb:479:in `generate'
	5: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/lib/earl_report.rb:559:in `earl_turtle'
	4: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/lib/earl_report.rb:559:in `each'
	3: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/lib/earl_report.rb:565:in `block in earl_turtle'
	2: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/lib/earl_report.rb:565:in `each'
	1: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/lib/earl_report.rb:566:in `block (2 levels) in earl_turtle'
/var/lib/gems/2.7.0/gems/earl-report-0.7.0/lib/earl_report.rb:574:in `ttl_entity': undefined method `map' for "http://champin.net/#pa":String (NoMethodError)
```

If I rename the file to `jena.ttl, I get 
```
Traceback (most recent call last):
	11: from /home/afs/gems/bin/earl-report:23:in `<main>'
	10: from /home/afs/gems/bin/earl-report:23:in `load'
	 9: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/bin/earl-report:100:in `<top (required)>'
	 8: from /var/lib/gems/2.7.0/gems/earl-report-0.7.0/lib/earl_report.rb:495:in `generate'
	 7: from /var/lib/gems/2.7.0/gems/haml-5.2.1/lib/haml/engine.rb:130:in `render'
	 6: from /var/lib/gems/2.7.0/gems/haml-5.2.1/lib/haml/engine.rb:130:in `eval'
	 5: from (haml):343:in `block in render'
	 4: from (haml):343:in `each_with_index'
	 3: from (haml):343:in `each'
	 2: from (haml):374:in `block (2 levels) in render'
	 1: from (haml):374:in `each'
(haml):377:in `block (3 levels) in render': undefined method `has_key?' for "http://champin.net/#pa":String (NoMethodError)
```

**Comment by gkellogg** [comment]
I saw this intermittently too, and I’ll look into it. Probably the simplest change to the CY script is to change it to `rake clean default` to ensure everything gets built dispite time stamps.

**Comment by afs** [comment]
This has two part - timestamps and small changes of content. Might the small content changes be related to timestamps and cached build?

The "rake clean" should be good - it does not take very long to run.

(Feel free to close this issue)

**Comment by gkellogg** [comment]
I would like to see why the failure is happening, even though we can work around it. If I find an issue I'll cross reference into earl_report.
