### ISSUE TITLE
Activate GitHub Wiki

### ISSUE THREAD

**Issue by akuckartz** [w3c/rdf-star#24]
That would help to compile links and other material such as pro and contra from the mailing list.

**Comment by pchampin** [comment]
What do you want to use the wiki for, compared to issues?

**Comment by pchampin** [comment]
Since this issue was raised, the ghpages have evolved from hosting just the spec to hosting a proper "homepage" for RDF*. Anyone can submit a PR with an additional page and a link to it from index.html. I think the wiki would be somewhat redundant with that. Would you agree @akuckartz ?

**Comment by pchampin** [comment]
Seeing no complain at my suggestion to close this issue, I'll do it. Anyone, comment if you feel it needs re-opening.
