### ISSUE TITLE
links to use cases don't work

### ISSUE THREAD

**Issue by rat10** [w3c/rdf-star#249]
the links to the use cases in Section 6.4.5 all 404 as they point to
 https://www.w3.org/2021/UCR/rdf-star-ucr.html
instead of
 https://w3c.github.io/rdf-star/UCR/rdf-star-ucr.html

**Comment by afs** [comment]
Thanks - the spec had relative URLs so, when published, didn't work any more.

@pchampin Can we change the published version in place?

**Comment by pchampin** [comment]
We can, and I just did :)
Note that another link to `../tests/` was also broken, and I fixed it as well on the published version.

**Comment by afs** [comment]
Published version checked (probably needs a hard-refresh to get the latest HTML).
