### ISSUE TITLE
invalid prefix declaration in RDF-star examples

### ISSUE THREAD

**Issue by odameron** [w3c/rdf-star#258]
The RDF-star examples in https://w3c.github.io/rdf-star/cg-spec/editors_draft.html use the SPARQL-like syntax in Turtle-star.

Example-1 (https://w3c.github.io/rdf-star/cg-spec/editors_draft.html#example-1) is
```PREFIX :    <http://www.example.org/>```

and should use
`@prefix :    <http://www.example.org/> .`
with a final full stop

**Comment by pchampin** [comment]
Actually, both syntaxes are valid in standard Turtle [1] (although this was an addition compared to the initial proposal [2]).

[1] https://www.w3.org/TR/turtle/
[2] https://www.w3.org/TeamSubmission/turtle/

**Comment by odameron** [comment]
ah by bad, sorry for the noise
(I am glad to have learned this, though, the two different syntaxes were cumbersome)
