### ISSUE TITLE
RDF-star IRI 404

### ISSUE THREAD

**Issue by wnybomTNA** [w3c/rdf-star#268]
According to [RDF-star and SPARQL-star (w3.org)](https://www.w3.org/2021/12/rdf-star.html#conventions) the rdf-star IRI should be http://www.w3.org/ns/rdf-star#
Why does the page there give 404?

**Comment by afs** [comment]
That is the namespace URI. Prefix declarations and XML namespaces do not require the URL to resolve to a document. 

The Community Group (CG) has produced a final report and the next step is in process to start a Working Group (WG), which can produce W3C standards.

While it is good practice to place an informative document at the namespace URL, it is also useful for it to be stable.

The working group may choose to populate the namespaces document. The outcome of the WG is not required to be compatible with the work of the CG.
