### ISSUE TITLE
Do we need more things in the 'conformance' section?

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star#3]
For the moment, we only have the boilerplate text generated by respec.

**Comment by hartig** [comment]
I don't think we need more in that section. However, let's keep this question open for the moment and revisit at some later point.

**Comment by pchampin** [comment]
I think we can reopen this and make a decision. Since the spec is mostly a list of "patches" on existing specs, I think we can defer to the conformance sections of the original specs. I think this goes without saying and does not even require any text in the 'Conformance' section of our report, but I may be convinced otherwise.

**Comment by afs** [comment]
Turtle and SPARQL have conformance as well -  sentence referring to the tests.

We should say something about the test suite because the RDF-star doc is "Concepts" and "Turtle-star" and "SPARQL-star". It is necessary so that there is a some stated conditions "supporting RDF-star". i.e.if some system uses the name "RDF-star" then basic level of requirements/expectation. Or anything is "RDF-star".

Maybe something like "system must be able to read one or more RDF-star syntaxes".

**Comment by pchampin** [comment]
this was discussed during today's meeting: https://w3c.github.io/rdf-star/Minutes/2021-10-01.html#t05

**Comment by pchampin** [comment]
this was discussed during today's meeting: https://w3c.github.io/rdf-star/Minutes/2021-11-12.html#t03

**Comment by afs** [comment]
It's not necessary to have more conformance but I think it is useful to say what a system that "supports RDF-star" means in some concrete behavioral terms.

In what way does a plain RDF 1.1 system "not support RDF-star"? It does not process the quoted triple syntax.

We could say something like:

- If a system has RDF input, then it accepts at least one RDF-star syntax as given by the test suite.
- If a system has RDF output, then it accepts at least one RDF-star syntax as given by the test suite.

allowing for systems that only input or only output. If it has no I/O in RDF syntax, e.g. API only, we don't say one way or the other if it supports RDF-star.

For SPARQL-star, it's easier - pass the syntax and evaluation test suites, and that means input of RDF-star data, with support for the quoted triple functions.

So a system that provides reification does not support RDF-star.

A system that translates input to internally to use reification (which will be restricted to some RDF-star isomorphic form) and reverses that for output, it does "support RDF-star". Functionally, it reads/writes RDF-star; reficiation is the implementation technique inside the black box.

**Comment by TallTed** [comment]
> * If a system has RDF output, then it accepts at least one RDF-star syntax as given by the test suite.

Rather than `accepts`, this should be `emits`, no?

**Comment by afs** [comment]
Yes - fixed the original. Thanks.
