### ISSUE TITLE
distinguish interpretation from representation

### ISSUE THREAD

**Issue by lisp** [w3c/rdf-star#32]
As a data service, from an architectural perspective, interpretation should be distinct from and cleanly layered over representation - both abstract and concrete, in order to facilitate implementation and assure the ability to support future use cases as knowledge evolves over time.

From this perspective, the standard treatment of blank node labels is an anti-requirement, the lessons of which should dissuade from unnecessarily restrictive relations between interpretation and representation.

The situation with blank node labels is a case where the interpretation was fixed, to treat them as referentially opaque. that was a mistake. it would have been better to separate the interpretation from the representation and to allow alternatives.

- https://lists.w3.org/Archives/Public/semantic-web/2009Nov/0040.html
- https://www.slideshare.net/PatHayes/blogic-iswc-2009-invited-talk
- http://videolectures.net/iswc09_hayes_blogic/ (which, just now, did not work)

**Comment by pfps** [comment]
@lisp Please consider submitting a use case to the working group, in https://github.com/w3c/rdf-ucr/issues.   

A few examples showing what distinctions you want to be able to make would likely help the working group as they determine how quoted triples should work in RDF 1.2.
