### ISSUE TITLE
SPARQL* semantics needs to be completed

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star#4]
The RFD* paper was not relying directly on the SPARQL11-QUERY spec, but on a paper by Pérez *et al.*, which can not(?) be used as a normative reference. So we need to adapt the definitions to those in the spec.

@hartig wrote:
> I have added the definition above for the moment. However, there is additional work to be done to define the semantics of such SPARQL* property path patterns. In fact, even for standard property path patterns, the semantics has to be extended to use them over RDF* graphs.

**Comment by hartig** [comment]
It seems you are mixing multiple things here. The note that you are quoting in your issue description was something that I had added into the spec draft explicitly for the definition of the notion of a [SPARQL* property path pattern](https://w3c.github.io/rdf-star/#dfn-ppp-star). Notice that this is somehow separate from the need to first copy over the existing definition of the SPARQL* query semantics into the spec.

**Comment by pchampin** [comment]
Sorry about the mix up... May be the best would be to close this issue and to open two new ones, more targetted?

**Comment by hartig** [comment]
Good idea ;-)

**Comment by hartig** [comment]
I have opened two separate issues for this one now: #7 and #8
