### ISSUE TITLE
Create a test suite

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star#40]
* [x] for the semantics (what RDF* graph should be entailed, under which entailment regime)
* [x] include the README of the test suite in the manifest.html
* [x] for Turtle*
* [x] for SPARQL* syntax (query, update)
* [x] for SPARQL* evaluation (query, update)

https://w3c.github.io/rdf-star/Minutes/2020-11-20.html#ActionSummary

**Comment by ericprud** [comment]
I assume the idea is to parse something and compare it to the abstract syntax. Does this depend on either a normative representation as a DataSet (so it can be represented as e.g.NQuads or RDF 1.1 TrIG) or two RDF*-specific languages like Turtle* and RDF/XML*?

**Comment by pchampin** [comment]
@ericprud 
> I assume the idea is to parse something and compare it to the abstract syntax.

The "semantics" test suite is more about entailment, so the idea is to parse a graph, and check if another graph is considered entailed by the former one (under the given entailment regime, which can be "simple", i.e. no specific inference).
One way to check that is to run against the first graph a SPARQL ASK query containing the second one. But some implementations may have other, more direct, ways to check entailment.

**Comment by pfps** [comment]
The current version of the test suite is described at https://w3c.github.io/rdf-star/tests/semantics/manifest.html
