### ISSUE TITLE
May an embedded triple be a graph name in SPARQLstar ?

### ISSUE THREAD

**Issue by JervenBolleman** [w3c/rdf-star#44]
Would the following be allowed?

```sparql
SELECT *
WHERE {
  GRAPH << ex:s ex:o ex:p >> {
   ?s ?p ?o .
 }
}
```
or
```
SELECT *
FROM << ex:s ex:o ex:p >> 
WHERE {
   ?s ?p ?o .
}
```

**Comment by hartig** [comment]
I would say: No. Why would someone want to have that?

Or are you just asking whether it is possible currently? In this case, the answer is that it is: no. The production [58] in the [SPARQL grammar](https://www.w3.org/TR/sparql11-query/#sparqlGrammar) covers the GRAPH clause as follows:
```
[58]  GraphGraphPattern  ::=  'GRAPH' VarOrIri GroupGraphPattern
```
The extension of this [grammar for SPARQL*](https://w3c.github.io/rdf-star/rdf-star-cg-spec.html#sparql-star-grammar) does not change this production. The same holds for the FROM clause.

**Comment by JervenBolleman** [comment]
I was just musing, and thinking of a historian who wants to group triples related to a statement but not directly related to the statement.

i.e. where the following would not be ideal.
```
<<ex:s ex:p ex:o>> ex:p1 ex:o2 .
<<<<ex:s ex:p ex:o>> ex:p1 ex:o2 >> ex:p3 ex:p4 .
```

In any case it might have an effect regarding compatibility to sparql 1.1 (not if embedded triples are blank nodes, but yes if embedded triples are IRIs).

**Comment by pchampin** [comment]
@JervenBolleman I also have a hard time figuring out what you are trying to achieve... It would be easier if your example was using more concrete names, in order to imagine in what kind of real situation this could be useful.

Also, regarding your remark:
> not if embedded triples are blank nodes, but yes if embedded triples are IRIs

Currently, embedded triples are *neither* blank nodes or IRIs, they are a thing of their own.

**Comment by pchampin** [comment]
@JervenBolleman would you object to closing this issue?

Note that I am personally a big fan of generalized RDF, where any kind of term can be used in any position. In this regard, generalized RDF-star would naturally allow embedded triples in any position, including graph name.

However, I think our focus here should be on RDF-star, not generalized RDF-star, which would open other cans of woms that are orthogonal to our concerns ("literals as subjects" come to mind... actually, this has been raised on the maling list recently).

The future WG might have a broader scope, but as a CG, I think we have enough on our plate already...

**Comment by JervenBolleman** [comment]
@pchampin I am happy to close the issue. If anyone really wants it as a feature they can reopen it.

Conculsion: SPARQL GraphNames may not be named by triples.
