### ISSUE TITLE
Undefined notation in SPARQL* "Evaluation semantics"

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star#5]
@hartig wrote:
> ⟦B⟧_G is not defined anywhere here, and neither is ⟦(tp AS ?v)⟧_G

Actually, the first time this notation is used, it says
>  ⟦B⟧_G (where ⟦B⟧_G is the evaluation of B over RDF* graph G)

where "evaluation" links to its definition, yet to be written in the ~Algebra~ Evaluation Semantics section.
So I consider this issue to be a duplicate of #4.

**Comment by hartig** [comment]
I think we should get rid of the "Algebra section" and, instead, put the definitions related to the query semantics directly into the [Evaluation Semantics section](https://w3c.github.io/rdf-star/#evaluation-semantics).

(Also, the "Algebra section" would not be about algebra, actually ;-)

**Comment by hartig** [comment]
I have created a more specific issue for this now: #8
