### ISSUE TITLE
Turtle* syntax tests

### ISSUE THREAD

**Issue by afs** [w3c/rdf-star#53]
This issue is for Turtle* syntax tests. 

A first set is provided PR #52.

**Comment by lisp** [comment]
have the two modes been ratified - with a distinction in interpretation anchored in the syntax?

**Comment by afs** [comment]
@lisp - they are syntax tests. As per PR, description:

> They test whether a parser accepts or rejects a file. There is no implication as what triples are generated which is left for a separate set of tests.

**Comment by lisp** [comment]
is the "annotation" syntax being considered for both modes?

**Comment by afs** [comment]
I put annotation examples in for discussion.

I would have thought annotation applied to both SA and PG modes and I see nothing in the discussion to suggest it is anything other than a convenience syntax for `:s :p :o. <<:s :p :o>>` (it's output is all the SA triples) and neatly collecting the triple term assertions together (the second example shows that for the modelling case of multiple provenance). But no decision.

Indeed, IMO it is one way to resolve the SA/PG choice.

**Comment by hartig** [comment]
> is the "annotation" syntax being considered for both modes?

No, the way I see it, adding the annotation gives us a way to cover both modes, where the annotation syntax is for PG mode.

By the way, there is a separate issue for the annotation syntax: #9

**Comment by hartig** [comment]
> have the two modes been ratified - with a distinction in interpretation anchored in the syntax?

That would be my desired outcome. However, nothing has been ratified yet.

**Comment by lisp** [comment]
the, the question becomes, is are the test suite projective or prescriptive?

**Comment by pchampin** [comment]
> the, the question becomes, is are the test suite projective or prescriptive?

The way as see it, nothing is prescriptive at the moment.

**Comment by pchampin** [comment]
@afs should we close this issue? This is not to mean that the corresponding test suite is complete -- in my view, it will always be possible to add new tests. But that's "normal process" and should not require an outstanding issue.

**Comment by afs** [comment]
I agree - the primary version of content is the documents and new issues can be raised for documents.
Closing an issue is not ending discussion.
