### ISSUE TITLE
FIND instead of BIND

### ISSUE THREAD

**Issue by hartig** [w3c/rdf-star#6]
Instead of reusing the keyword BIND for SPARQL* (as in my original proposal), we may want to consider using a different keyword for this functionality because the behavior is a bit different. For instance, @klinovp has mentioned this issue in [an email on the mailing list](https://lists.w3.org/Archives/Public/public-rdf-star/2019Nov/0000.html). In [another email](https://lists.w3.org/Archives/Public/public-rdf-star/2020Aug/0008.html), @afs has proposed to use the keyword FIND instead.

**Comment by pchampin** [comment]
It seems to me that the arguments raised by @klinovp in his email mostly applied to (what was then known as) PG mode. In the current state of the spec, I find the proposed extension of BIND (to support embedded triples) consistent with its other uses: you simply pick or construct a new term and assign it to a variable. Whether that term is already used or not in the graph is irrelevant, even for embedded triples.

**Comment by hartig** [comment]
No, the SPARQL-star version of BIND, as it is currently defined, can **not** construct new triples. It can only match triples that are present in the queried graph.

The reason why I had defined it like this (already in the original paper) has nothing to do with PG mode but with the fact that it actually adds expressive power to the language. Without it, there is no way a user can bind a variable to asserted triples in the graph.

The use case of constructing new triples and binding them to a variable can be captured by introducing dedicated built-in functions that can then be used with the standard BIND operator. Some systems (including Jena) are already providing such built-in functions and we may decide to include them in the spec, but that's a separate issue.

**Comment by afs** [comment]
I don't think having a special way to create triple-terms which is different to other terms makes sense overall. It is also blocking to use in expressions if it reuses a keyword.

Hence FIND for matching, BIND for creating.

At the moment, the duplicate meaning of BIND blocks functions use of triple terms in expressions. The grammar can't  include triple terms in the general expression productions without it being ambiguous. If they aren't in expressions, they can't be arguments to functions to access the subject/predicate/object, whether built-in or extension functions.

Accessor functions are necessary to complete the ways to make triple-terms : how to make a new triple term that has the same subject as an existing one.

**Comment by hartig** [comment]
It seems we are on the same page.

I can create a PR that renames the SPARQL-star version of BIND to FIND. However, let's postpone this to after the work on PR #106 (annotation syntax for SPARQL-star) has been finished and that PR has been merged.

Additionally, I have created separate issue for the possibility to enable users to construct triples: #109

**Comment by afs** [comment]
Agreed - postpone it for now.

I have checked that adding `<<>>` to expressions by adding it to `PrimaryExpression` works as language syntax. 

The next question is whether any additional spec text is need about evaluation to ensure "eval <<:s :p ?o>>" is an error for unbound ?o. It does not look like it at the moment but more checking needed.

Given a direct `<<>>` in `PrimaryExpression`, and the functions in #109, we may not need the BIND/FIND form here.

```
?s ?p ?o
BIND(<<?s ?p ?o>> AS ?t1)
```
The `TRIPLE` function is more general because it allows expressions as arguments:
```
?s ?p ?o
BIND(TRIPLE(?s, ?p, ?o+1) AS ?t2)
```
and one possibility is to define expression `<<?s ?p ?o>>` as syntactic sugar for `triple(?s, ?p, ?o)`.

**Comment by pchampin** [comment]
> No, the SPARQL-star version of BIND, as it is currently defined, can not construct new triples. It can only match triples that are present in the queried graph.

Oh, how wrong I was. I should have read the definitions more carefully, sorry...

 > The `TRIPLE` function is more general (...)

It is indeed.

**Comment by hartig** [comment]
@afs I assume that [your comment](https://github.com/w3c/rdf-star/issues/6#issuecomment-782890331) is about the construction of triples in BIND. However, just for the record:
> The next question is whether any additional spec text is need about evaluation to ensure "eval <<:s :p ?o>>" is an error for unbound ?o.

If this statement is about construction of triples in BIND, then yes. On the other hand, if this statement is about matching of triples by using FIND, then I don't see this as an issue. In fact, I don't think there should be a requirement that variables mentioned in a FIND clause need to be bound before. The evaluation semantics of this operator does not need it. In contrast, any variable that is still unbound at the point when the operator is evaluated in a query plan will be bound in a compatible way. In this sense, the FIND operator works essentially like a BGP.

**Comment by afs** [comment]
It is about the use of `<<>>` syntax in expressions.

> FIND operator works essentially like a BGP.

That's what I'm discovering.

I'm not sure now there is a need for this operation in RDF-star. It made sense when it was (in implementation speak) RDF\* times looking up in a triple index and creating embedded triples based on a match; a significant building block for PG-ish behaviour.

In RDF-star, It can be written using a graph pattern and use of regular `BIND`+`TRIPLE`.

```
?s ?p ?o . BIND(TRIPLE(?s,?p,?o) AS ?t)
```
and locating embedded triples is:
```
{ <<?x ?y ?z>>  ?p ?o . } UNION {  ?s ?p <<?x ?y ?z>>  . }
```
or (depending on what else in the pattern) using a pattern like:
```
?t :predicate :object . FILTER(isTRIPLE(?t))
```
To return an embedded triple:
```
SELECT (TRIPLE(?s, ?p, ?o) AS ?T) { ... }
```
```
CONSTRUCT { << ?s ?p ?o >> :q :z } WHERE { ... }
```
 Am I missing something?

**Comment by afs** [comment]
Let's take `<< >>` syntax in expressions to issue #109.

**Comment by hartig** [comment]
> I'm not sure now there is a need for this operation in RDF-star.

You are right!

Another use case of `FIND(<<?s ?p ?o>> AS ?t)` was to "go" from a binding for ?t to add bindings for ?s, ?p, and ?o. However, with the accessor functions in #109, this use case can also captured by using the standard BIND operator.

Hence, if we add the constructor and the accessors as proposed in #109, we can get rid of FIND altogether. That would be a nice simplification.

**Comment by hartig** [comment]
The agreement in the telco today was to remove the SPARQL-star version of BIND (a.k.a. FIND) from the spec.

**Comment by hartig** [comment]
Everything related to the SPARQL-star version of BIND (a.k.a. FIND) has been removed from the spec now (see PR #115). Hence, this issue here can be closed now.
