### ISSUE TITLE
Property path patterns in SPARQL*

### ISSUE THREAD

**Issue by hartig** [w3c/rdf-star#7]
I have added the definition of a [SPARQL* property path pattern](https://w3c.github.io/rdf-star/rdf-star-cg-spec.html#dfn-ppp-star) into the draft just for the sake of having such a definition. We need to think about whether it is useful to add this to SPARQL*, in which case we need to define the semantics of such SPARQL* property path patterns.

In fact, no matter what we decide, even for [standard property path patterns](https://www.w3.org/TR/sparql11-query/#defn_PropertyPathPattern), the semantics may have to be extended to use them over [RDF* graphs](https://w3c.github.io/rdf-star/rdf-star-cg-spec.html#dfn-graph).

**Comment by hartig** [comment]
I have looked through this in detail now and I would say that we actually do not need to do anything here---at least, if we make two assumptions (which we may make explicit in the spec):
1. We assume SA mode.
2. We assume that every mention of the words "RDF term" and "term" in [Sec.18.4 of the SPARQL 1.1 spec](https://www.w3.org/TR/sparql11-query/#PropertyPathPatterns) is meant to refer to our notion of an RDF* term. 

The first assumption is necessary for the following reason.

In SA mode, every embedded triple t that is not also contained directly in the given RDF* graph G (i.e., t ∉ G) is not asserted and, thus, should be ignored during path pattern matching. Ignoring such an embedded triple t happens trivially with the current definitions of property path pattern evaluation in [Sec.18.4 of the SPARQL 1.1 spec](https://www.w3.org/TR/sparql11-query/#PropertyPathPatterns). 

In contrast, an embedded triple t' that is also contained directly in the given RDF* graph G (i.e., t' ∈ G) is asserted and, thus, must not be ignored during path pattern matching. However, due to the fact that t' ∈ G, the triple is considered by the current definitions of property path pattern evaluation, as desired.

The second assumption is necessary to be able to consider nested RDF* triples (i.e., triples that have an embedded triple as their subject or their object) during path pattern matching. Then, a path that matches a property path expression may start from an embedded triple or may end in an embedded triple (or both). It is even possible that intermediate nodes along such a path are embedded triples.

As an example, consider the RDF* graph in the following snippet of Turtle*.
```
<<:s1 :p1 :o1>>  :q1  <<:s2 :p2 :o2>> .
<<:s2 :p2 :o2>>  :q2  :a .
```
...and consider the following SPARQL* query.
```
SELECT ?x ?y WHERE {
   ?x  :q1/:q2*  ?y 
}
```
The result of this query over the RDF* graph consists of two solution mappings:
* μ1 = { ?x -> t1, ?y -> t2 } and
* μ2 = { ?x -> t1, ?y -> :a },

where t1 is the triple (:s1,:p1,:o1) and t2 is the triple (:s2,:p2,:o2).

**Comment by afs** [comment]
See also #65.

**Comment by pchampin** [comment]
I think this issue can now be closed. @hartig @afs do you concur?

**Comment by afs** [comment]
Concur

**Comment by hartig** [comment]
Concur
