### ISSUE TITLE
Consider defining an IRI to represent the type of an embedded triple or triple pattern

### ISSUE THREAD

**Issue by kasei** [w3c/rdf-star#77]
This would be useful for representing queries and metadata in a structured way. For example, representing a SPARQL* query in a format such as [SPIN](https://spinrdf.org) or indicating the type of a database column using [R2RML's](https://www.w3.org/ns/r2rml) `termType`. This would work alongside other IRIs such as `rdfs:Literal` and `rr:BlankNode`.

**Comment by afs** [comment]
Related: SHACL [NodeKind](https://www.w3.org/TR/shacl/#NodeKindConstraintComponent).

**Comment by hartig** [comment]
Just saw that this issue is a duplicate of #102

**Comment by pchampin** [comment]
That's right. Although this one was here first, most of the discussion happened on #102, so I'll close this one as a dublicate. No offense @kasei ;)
