### ISSUE TITLE
Section 1.2 links to 1999 RDF spec to explain reification

### ISSUE THREAD

**Issue by rat10** [w3c/rdf-star#82]
Is there a specific reason that section 1.2 links the term "reification" to the "Resource Description Framework (RDF) Model and Syntax Specification" W3C Recommendation from 22 February 1999? The RDF 1.1 Semantics from 2014 is the currently authoritative spec, the RDF 1.0 Primer from 2004 features an IMO very accessible introduction.
IIUC the 1999 spec doesn't differentiate between triple type and occurrence whereas the later specs do explain the difference in detail. To properly describe the differences of reification in RDF* and RDF the current spec and its direct predecessor from 2004 seem more appropriate.

**Comment by TallTed** [comment]
This is an important observation.  For RDF(etc)-star to be treated as seems to be desired, it *must* proceed from RDF(etc) 1.1 (or later, such as SPARQL 1.2, if it proceeds to ratification before RDF(etc)-star).

**Comment by pchampin** [comment]
@bobdc did you have a good reason to point to the 1999 REC? Otherwise, I can see two replacement candidatates from the latest spec:
* from RDF-Schema: https://www.w3.org/TR/rdf-schema/#ch_reificationvocab
* from RDF 1.1 Semantics: https://www.w3.org/TR/rdf11-mt/#reification

**Comment by bobdc** [comment]
@pchampin sorry about that, I guess my bookmarks to the specs are old. Please go ahead and update them.
