### ISSUE TITLE
get back admin priviledge on BBB or find a new telco platform

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star#85]

**Comment by hartig** [comment]
We can start using Zoom via my university's subscription. It's stable. I am using it for lectures with 100+ students.

**Comment by pchampin** [comment]
Thanks @hartig for this backup plan. I just got back my admin privileges on BBB, so there is no urge to change, unless people prefer Zoom.

Question: can you delegate (to me or anyone else) some privileges on a Zoom room hosted at your university? The main requirement is that the chair be able to mute participants that forget to do so...

**Comment by hartig** [comment]
The host of a Zoom meeting can make other participant co-hosts, which gives them the privilege to mute participants. However, this can be done by the host only during the meeting, not before.

Another, more suitable option would be the "alternative host" feature but, unfortunately, this can only be used for people who are in the same organization as the actual host.
