### ISSUE TITLE
SPARQL-star update example in the overview/primer part

### ISSUE THREAD

**Issue by hartig** [w3c/rdf-star#94]
The overview/primer part of the report should also contain an example that hints at the fact that the spec also covers updates.

**Comment by hartig** [comment]
This issue may be addressed by simply moving the informal-overview section that PR #98 adds to Section 5 into the general overview/primer part.

**Comment by pchampin** [comment]
@hartig I didn't follow your suggestion above, and created a new example for §1. I thought that the informal description in §5 was too detailed for the intro (but of course, it stays as is in §5).
